services:
  app:
    build: .
    image: keitaro-tools
    command: python /app/src/main.py
    volumes:
      - ./src:/app/src
      - ./landings_archives:/app/landings_archives
      - ./offers_archives:/app/offers_archives
    environment:
      KEITARO_URL: ${KEITARO_URL}
      KEITARO_API_KEY: ${KEITARO_API_KEY}

  clamav:
    image: clamav/clamav:latest