import os

KEITARO_URL = os.getenv("KEITARO_URL")
KEITARO_API_KEY = os.getenv("KEITARO_API_KEY")
KEITARO_OLD_URL = os.getenv("KEITARO_OLD_URL")
KEITARO_OLD_API_KEY = os.getenv("KEITARO_OLD_API_KEY")
KEITARO_ASIA_URL = os.getenv("KEITARO_ASIA_URL")
KEITARO_ASIA_API_KEY = os.getenv("KEITARO_ASIA_API_KEY")