MACROS_RULES = [
    {
        "id": "head_fbpixel",
        "type": "insert_before",
        "target": "</head>",
        "content": "{_fbpixel}",
        "marker": "{_fbpixel}",
        "required": True,
    },
    {
        "id": "head_back_script",
        "type": "insert_before",
        "target": "</head>",
        "content": '<script>\nwindow.back = "{offer}";\n</script>',
        "marker": "window.back",
        "required": True,
    },
    {
        "id": "head_back_macro",
        "type": "insert_before",
        "target": "</head>",
        "content": "{_back}",
        "marker": "{_back}",
        "required": True,
    },
    {
        "id": "input_subid",
        "type": "upsert_input",
        "name": "subid",
        "content": '<input type="hidden" name="subid" value="{_subid}">',
        "required": True,
    },
    {
        "id": "input_ip",
        "type": "upsert_input",
        "name": "ip",
        "content": '<input type="hidden" name="ip" value="{_ip}">',
        "required": True,
    },
    {
        "id": "input_country",
        "type": "upsert_input",
        "name": "country",
        "content": '<input type="hidden" name="country" id="country">',
        "required": True,
    },
    {
        "id": "input_phonecc",
        "type": "upsert_input",
        "name": "phonecc",
        "content": '<input type="hidden" name="phonecc" id="phonecc">',
        "required": True,
    },
    {
        "id": "input_funnel",
        "type": "upsert_input",
        "name": "funnel",
        "content": '<input type="hidden" name="funnel" value="{_offer_value:funnel}">',
        "required": True,
    },
    {
        "id": "input_aff_sub2",
        "type": "upsert_input",
        "name": "aff_sub2",
        "content": '<input type="hidden" name="aff_sub2" value="{sub_id_14}">',
        "required": True,
    },
    {
        "id": "input_lang",
        "type": "upsert_input",
        "name": "lang",
        "content": '<input type="hidden" name="lang" value="{sub_id_15}">',
        "required": True,
    },
    {
        "id": "body_phonemacros",
        "type": "insert_before",
        "target": "</body>",
        "content": "{_phonemacros}",
        "marker": "{_phonemacros}",
        "required": True,
    },
]